spring.datasource.url=jdbc:postgresql://localhost:5432/payroll_db
spring.datasource.username=postgres
spring.datasource.password=1804
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080
server.servlet.session.timeout=30m

# Spring Mail – reset hasła (WF.17)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=twoj@gmail.com
spring.mail.password=app-password
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true

app.base-url=http://localhost:8080
app.password-reset.token-expiry-hours=1
